FashionLike/Controllers/PosteoController.cs
using FashionLike.Models;
using FashionLike_Modelos.Models;
using FashionLike_AccesoDatos.Datos;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore.Metadata;
using FashionLike_Utilidades;
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Authorization;
using Microsoft.Extensions.Logging;
using FashionLike_AccesoDatos.Datos.Repositorio.IRepositorio;  // Agregar esta referencia para el logger

namespace FashionLike.Controllers
{
    public class PosteoController : Controller
    {      
        private readonly IWebHostEnvironment _webHostEnvironment;
        private readonly ILogger<PosteoController> _logger;  // Declara el logger
        private readonly IRepositorio<Posteo> _repo;
        private readonly IPosteoRepositorio _posteo;

        // Inyección de dependencias del logger
        public PosteoController(ApplicationDBContext db, IWebHostEnvironment webHostEnvironment, ILogger<PosteoController> logger, IRepositorio<Posteo> repo, IPosteoRepositorio posteo)
        {
            _webHostEnvironment = webHostEnvironment;
            _logger = logger;  // Asigna el logger
            _repo = repo;
            _posteo = posteo;
        }

        [Authorize]
        public IActionResult Index()
        {
            try
            {
                IEnumerable<Posteo> ListaPosteos = _repo.ObtenerTodos();
                // IEnumerable<Posteo> ListaPosteos = _db.Posteos;
                _logger.LogInformation("Accediendo a la lista de posteos.");
                return View(ListaPosteos);
            }
            catch (Exception ex)
            {
                _logger.LogError($"Error al obtener los posteos: {ex.Message}");
                return View("Error");
            }
        }

        //Get
        public IActionResult Upsert(int? Id)
        {
            try
            {
                Posteo posteo = new Posteo();
                if (Id == null)
                {
                    _logger.LogInformation("Creando un nuevo posteo.");
                    return View(posteo); //Enviamos posteo vacío para llenarlo
                }
                else
                {
                    if (Id.HasValue) 
                    {
                        posteo = _repo.Obtener(Id.Value); 
                        if (posteo == null)
                        {
                            _logger.LogWarning($"No se encontró un posteo con Id = {Id.Value}");
                            return NotFound();
                        }
                    }
                    else
                    {
                        _logger.LogWarning("El Id recibido es nulo.");
                        return NotFound();
                    }
                }
                return View(posteo);
            }
            catch (Exception ex)
            {
                _logger.LogError($"Error al acceder al posteo: {ex.Message}");
                return View("Error");
            }
        }

        //Crear o actualizar posteo
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Upsert(Posteo posteo)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    var files = HttpContext.Request.Form.Files;
                    string webRootPath = _webHostEnvironment.WebRootPath;

                    if (posteo.Id == 0)
                    {
                        _logger.LogInformation("Creando un nuevo posteo.");
                        // Lógica para crear un posteo
                        string upload = webRootPath + WC.ImagenRuta;
                        string fileName = Guid.NewGuid().ToString();
                        string extension = Path.GetExtension(files[0].FileName);

                        using (var FileStream = new FileStream(Path.Combine(upload, fileName + extension), FileMode.Create))
                        {
                            files[0].CopyTo(FileStream);
                        }
                        posteo.VotosPositivos = 0;
                        posteo.VotosNegativos = 0;
                        posteo.ImagenUrl = fileName + extension;
                        posteo.Fecha = DateTime.Now;
                        _repo.Agregar(posteo);
                        //_db.Posteos.Add(posteo);
                        _logger.LogInformation($"Posteo con Id {posteo.Id} creado.");
                    }
                    else
                    {
                        _logger.LogInformation($"Actualizando el posteo con Id {posteo.Id}.");
                        var objPosteo = _posteo.ObtenerPosteoModificar(posteo.Id);
                       // var objPosteo = _db.Posteos.AsNoTracking().FirstOrDefault(p => p.Id == posteo.Id);
                        if (objPosteo == null)
                        {
                            _logger.LogWarning($"Posteo con Id {posteo.Id} no encontrado para actualizar.");
                            return NotFound();
                        }

                        if (files.Count > 0)
                        {
                            string upload = webRootPath + WC.ImagenRuta;
                            string fileName = Guid.NewGuid().ToString();
                            string extension = Path.GetExtension(files[0].FileName);

                            var anteriorFile = Path.Combine(upload, objPosteo.ImagenUrl);
                            if (System.IO.File.Exists(anteriorFile))
                            {
                                System.IO.File.Delete(anteriorFile);
                            }

                            using (var FileStream = new FileStream(Path.Combine(upload, fileName + extension), FileMode.Create))
                            {
                                files[0].CopyTo(FileStream);
                            }
                            posteo.ImagenUrl = fileName + extension;
                        }
                        else
                        {
                            posteo.ImagenUrl = objPosteo.ImagenUrl;
                        }
                        _repo.Actualizar(posteo);
                       // _db.Posteos.Update(posteo);
                    }
                    _repo.Guardar();
                    //_db.SaveChanges();
                    _logger.LogInformation("Posteo guardado correctamente.");
                    return RedirectToAction("Index");
                }
                else
                {                                  
                        foreach (var error in ModelState.Values.SelectMany(v => v.Errors))
                        {
                            _logger.LogWarning($"Error en el modelo: {error.ErrorMessage}");
                        }
                        return View(posteo);                   
                }
            }
            catch (Exception ex)
            {
                _logger.LogError($"Error al guardar el posteo: {ex.Message}");
                return View("Error");
            }
        }

        //Eliminación de posteo
        public IActionResult Eliminar(int? Id)
        {
            try
            {          
                if (Id.HasValue)
                {
                    Posteo posteo = _repo.Obtener(Id.Value);
                    if (posteo == null)
                    {
                        _logger.LogWarning($"No se encontró un posteo con Id = {Id.Value}");
                        return NotFound();
                    }
                    return View(posteo);
                }
                else
                {
                    _logger.LogWarning("El Id recibido es nulo.");
                    return NotFound();
                }                                                   
            }
            catch (Exception ex)
            {
                _logger.LogError($"Error al acceder al posteo para eliminar: {ex.Message}");
                return View("Error");
            }
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Eliminar(Posteo posteo)
        {
            try
            {
                if (posteo == null)
                {
                    _logger.LogWarning("Posteo nulo al intentar eliminar.");
                    return NotFound();
                }

                string upload = _webHostEnvironment.WebRootPath + WC.ImagenRuta;
                var anteriorFile = Path.Combine(upload, posteo.ImagenUrl);
                if (System.IO.File.Exists(anteriorFile))
                {
                    System.IO.File.Delete(anteriorFile);
                }
                _repo.Remover(posteo);
                //_db.Posteos.Remove(posteo);
                _repo.Guardar();
                //_db.SaveChanges();

                _logger.LogInformation($"Posteo con Id {posteo.Id} eliminado.");
                return RedirectToAction("Index");
            }
            catch (Exception ex)
            {
                _logger.LogError($"Error al eliminar el posteo: {ex.Message}");
                return View("Error");
            }
        }
    }
}

FashionLike/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - FashionLike</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/FashionLike.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/fontawesome/css/all.css" />
    <link href="https://cdn.jsdelivr.net/npm/summernote@0.9.0/dist/summernote.min.css" rel="stylesheet">
    <link href="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.css" rel="stylesheet" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">FashionLike</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between flex-row-reverse">
                    <partial name="_LoginPartial" />
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        @if (User.IsInRole(FashionLike_Utilidades.WC.AdminRole))
                        {
                                <li class="nav-item dropdown">
                              <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                                  Administrar
                              </a>
                              <ul class="dropdown-menu">
                                  <li class="dropdown-item">
                                      <a class="nav-link text-dark" asp-area="Identity" asp-page="/Account/Register">Crear nuevo usuario</a>
                                  </li>
                                  <li class="dropdown-item">
                                      <a class="nav-link text-dark" asp-area="" asp-controller="Posteo" asp-action="Index">Posteos</a>
                                  </li>
                              </ul>
                            </li>     
                        }
                                                                   
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            <partial name="_Notificaciones"></partial>
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - FashionLike - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacidad</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="https://unpkg.com/sweetalert/dist/sweetalert.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/summernote@0.9.0/dist/summernote.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.js"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

FashionLike/Views/Shared/_Notificaciones.cshtml
@using FashionLike_Utilidades

@if(TempData[WC.Exitoso] != null)
{
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script type="text/javascript"
        src="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/js/toastr.min.js"></script>
    <script>
        toastr.success('@TempData[WC.Exitoso]');
    </script>
}@if (TempData[WC.Error] != null)
{
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script type="text/javascript"
            src="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/js/toastr.min.js"></script>
    <script>
        toastr.error('@TempData[WC.Error]');
    </script>
}